name: targowisko
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.0+2
  async: 2.3.0
  photo_view: 0.5.0
  meta: 1.1.8
  url_launcher: 5.1.1
  file_picker: 1.4.0+1
  auto_size_text: 2.1.0
  cached_network_image: 2.0.0-rc
  bloc: 0.15.0
  flutter_bloc: 0.21.0
  flutter_facebook_login: 3.0.0
  cupertino_icons: ^0.1.2
  flutter_svg: 0.14.3
  image_picker: 0.6.2+1
  transparent_image: 1.0.0

dev_dependencies:
  build_runner: 1.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/market_icon.png
    - assets/svg/facebook.svg
    - assets/market_placeholder.jpg
    - assets/product_icon.png
    - assets/seller_icon.png
    - assets/coin.png
    - assets/animals.jpg
    - assets/antiques.jpg
    - assets/automotive.jpg
    - assets/food.jpg
    - assets/fruits.jpg
    - assets/real_estate.jpg
    - assets/vegetables.jpg
    - assets/clothing.jpg
    - assets/cosmetics.jpg
    - assets/other.jpg
    - assets/electronics.jpg
    - assets/user.png
    - assets/food_spinner.gif

  fonts:
    - family: pacifico
      fonts:
        - asset: fonts/pacifico.ttf
